//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinanceServer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransAction
    {
        public int ActivityID { get; set; }
        public string Activity_Type { get; set; }
        public System.DateTime Date_of_Activity { get; set; }
        public decimal Value_of_Activity { get; set; }
        public string Description_of_Activity { get; set; }
        public string Type_Of_Expense { get; set; }
    }
}
